import Vue from 'vue';
// import ElementUI from 'element-ui';
// import 'styles/theme-chalk/reset.css';
import 'styles/theme-chalk/base.css';
import 'styles/theme-chalk/loading.css';
// import 'styles/theme-chalk/button-group.css';
import 'styles/theme-chalk/button.css';
// import 'styles/theme-chalk/carousel-item.css';
// import 'styles/theme-chalk/carousel.css';
// import 'styles/theme-chalk/checkbox-button.css';
// import 'styles/theme-chalk/checkbox-group.css';
// import 'styles/theme-chalk/checkbox.css';
// import 'styles/theme-chalk/radio-button.css';
// import 'styles/theme-chalk/radio-group.css';
// import 'styles/theme-chalk/dropdown-item.css';
// import 'styles/theme-chalk/dropdown-menu.css';
// import 'styles/theme-chalk/dropdown.css';
// import 'styles/theme-chalk/collapse-item.css';
// import 'styles/theme-chalk/collapse.css';
// import 'styles/theme-chalk/input.css';
// import 'styles/theme-chalk/input-number.css';
import 'styles/theme-chalk/icon.css';
// import 'styles/theme-chalk/menu-item.css';
// import 'styles/theme-chalk/menu-item-group.css';
// import 'styles/theme-chalk/menu.css';
// import 'styles/theme-chalk/submenu.css';
import 'styles/theme-chalk/option-group.css';
import 'styles/theme-chalk/option.css';
// import 'styles/theme-chalk/switch.css';
// import 'styles/theme-chalk/popover.css';
import 'styles/theme-chalk/pagination.css';
// import 'styles/theme-chalk/select.css';
import 'styles/theme-chalk/select-dropdown.css';
// import 'styles/theme-chalk/scrollbar.css';
import 'styles/theme-chalk/radio.css';
// import 'styles/theme-chalk/table.css';
// import 'styles/theme-chalk/table-column.css';
// import 'styles/theme-chalk/date-picker.css';
// import 'styles/theme-chalk/time-picker.css';
// import 'styles/theme-chalk/time-select.css';
// import 'styles/theme-chalk/tooltip.css';
// import 'styles/theme-chalk/row.css';
// import 'styles/theme-chalk/col.css';
/**
 * 直接引入lib中的js文件
 */

import select from 'element-ui/lib/select.js';
import button from 'element-ui/lib/button.js';
import pagination from 'element-ui/lib/pagination.js';
// import table from 'element-ui/lib/table.js';
// import tableColumn from 'element-ui/lib/table-column.js';
// import dataPicker from 'element-ui/lib/date-picker.js';
// import checkboxGroup from 'element-ui/lib/checkbox-group.js';
// import checkbox from 'element-ui/lib/checkbox.js';
// import radioGroup from 'element-ui/lib/radio-group.js';
// import radioButton from 'element-ui/lib/radio-button.js';
import menu from 'element-ui/lib/menu.js';
import menuItem from 'element-ui/lib/menu-item.js';
import input from 'element-ui/lib/input.js';
import option from 'element-ui/lib/option.js';
// import row from 'element-ui/lib/row.js';
// import col from 'element-ui/lib/col.js';

Vue.component(select.name, select);
Vue.component(button.name, button);
// Vue.component(table.name, table);
// Vue.component(tableColumn.name, tableColumn);
Vue.component(pagination.name, pagination);
// Vue.component(dataPicker.name, dataPicker);
// Vue.component(checkboxGroup.name, checkboxGroup);
// Vue.component(checkbox.name, checkbox);
// Vue.component(radioButton.name, radioButton);
// Vue.component(radioGroup.name, radioGroup);
Vue.component(menu.name, menu);
Vue.component(menuItem.name, menuItem);
Vue.component(input.name, input);
Vue.component(option.name, option);
// Vue.component(row.name, row);
// Vue.component(col.name, col);

